title: Respositorio sobre Transparencia
description: Referencias, leyes, tutoriales, ejemplos, aplicaciones y recursos sobre transparencia.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker